const public_key =
  "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu0OXd52nCDKzb9rq68b/yAs4MAECTwwOfxOC5lmXvmt7LaQ0Ttg9zQljhqPQjb6Ay2lSUuklN6YCUBwmnzn+IoevrVfxvVP/0qfXouGPOEoUb+wH1IywaxBBah5kKMSOJmZLs+N0N8jgMUVp4HkfdPZ1oVDy3Pql7jgBpaLoL6hjedEBMU56AiUzVXqwr+zTmzCEM3wIgPhdUxYa3MhPY+DetWRaSZAenYVzwAcTMUMS9Y+3zda0WjAPvrqgUvtuSVJJkkrAYB7UN/lnOcSsNefDppFGJh6AxEljxo2k0qB5uqnG9owbwIhJGUAEkLRlZAxhzM3FsO/DxshMOpGN9QIDAQAB";

const api_financeiro = "https://api-financeiro.sumare.edu.br/api-csh-pagbank"

export { public_key, api_financeiro };